kind: pipeline
type: docker
name: susy-extractor

trigger:
  branch:
    - master
    - develop

pipeline:
  publish-susy-extractor:
    image: plugins/docker
    dockerfile: ./Dockerfile
    context: .
    repo: gravityhuborg/susy-extractor
    tags: [latest, v2]
    secrets: [ docker_username, docker_password ]
    when:
      branch:
        - master
        - develop
